seed: 0

env: Taskography
env_kwargs: 
  sampler: rearrangement
  sampler_kwargs:
    domain_filepath: domains/taskographyv2.pddl
    scene_graph_filepath: null
    complexity: 1
    bagslots: null
  data_dir: $DATA/3dscenegraph
  split: tiny
  episodes_per_scene: 1
